name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
    steps:
      - uses: actions/checkout@v4
      - run: npm install --legacy-peer-deps
      - run: npm run build
      - run: npx gh-pages -d dist