name: Automated Tests

on:
  push:
    branches: [ main, master, develop, dev ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        rm -rf node_modules package-lock.json
        npm install --omit=optional
        npm install @rollup/rollup-linux-x64-gnu || true
    
    - name: Run tests
      run: npm run test:run
